version: "3.8"

services:
  front:
    image: sermalenk/skypro-front:lesson-38
    restart: always
    ports:
      - "82:80"
    depends_on:
      api:
        condition: service_started
      collect_static:
        condition: service_completed_successfully
    volumes:
      - django_static:/usr/share/nginx/html/static
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  api:
    build: .
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    environment:
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - ./toDoListProject/:/todolist/toDoListProject

  collect_static:
    build: .
    env_file: .env
    entrypoint: ''
    volumes:
      - django_static:/todolist/static/
    command: python3 manage.py collectstatic -c --no-input


  migrations:
    build: .
    env_file: .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      postgres:
        condition: service_healthy
    command: python manage.py migrate

  postgres:
    image: postgres:12.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    restart: always
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -U ${DB_USER} -d ${DB_DATABASE}
      interval: 5s
      timeout: 5s
      retries: 15

  telegram_bot:
    build: .
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy
      api:
        condition: service_started
    command: python manage.py runbot

volumes:
  postgres_data:
  django_static:
