name: Build and deploy action
on: [push]
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      # Копируем код из репозитория в runner
      - name: clone code 
        uses: actions/checkout@v2
     # Собираем
      - name: docker build
        run: docker build -t mvladlena85/todolist:$GITHUB_REF_NAME-$GITHUB_RUN_ID .
      - name: docker login
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: docker push
        run: docker push mvladlena85/todolist:$GITHUB_REF_NAME-$GITHUB_RUN_ID
